spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeedb
    username: root            
    password:           
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update        # dev: update / create-drop ; prod: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
